name: Android Go Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build and Bind
        run: |
          # الدخول للمجلد الذي يحتوي على الكود
          cd anabelrat
          
          # تهيئة الموديول داخل المجلد
          go mod init anabelrat || true
          
          # تثبيت الأدوات
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          
          # تهيئة gomobile وتحميل المكتبات
          $(go env GOPATH)/bin/gomobile init
          go get golang.org/x/mobile/bind
          go mod tidy
          
          # البناء من داخل المجلد وإخراج الملف للخارج
          $(go env GOPATH)/bin/gomobile bind -target=android -androidapi 30 -v -o ../anabelrat.aar .

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: anabelrat-library
          path: anabelrat.aar
