name: Android Go Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: false

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build and Bind
        run: |
          cd anabelrat
          echo "Installing gomobile..."
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          
          export PATH=$PATH:$(go env GOPATH)/bin
          
          echo "Initializing gomobile..."
          gomobile init
          
          echo "Running go mod tidy..."
          go mod tidy
          
          echo "Building AAR..."
          gomobile bind -target=android -androidapi 30 -v -o ../anabelrat.aar .

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: anabelrat-library
          path: anabelrat.aar
